export const courses = [
    {
      id: 1,
      title: "Introducción a Python",
      category: "Programación",
      level: "Principiante",
      levelColor: "green",
      description: "Aprende los fundamentos de Python desde cero...",
      image:
        "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800",
      duration: "8 semanas",
      students: 32,
      classes: 8,
      link: "/python",
    },
    {
      id: 2,
      title: "Data Science",
      category: "Data science",
      level: "Intermedio",
      levelColor: "orange",
      description: "Domina análisis de datos y machine learning...",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
      duration: "12 semanas",
      students: 856,
      classes: 0,
      link: "/data-science",
    },
    {
      id: 3,
      title: "Django",
      category: "Desarrollo web",
      level: "Intermedio",
      levelColor: "orange",
      description: "Construye aplicaciones web completas usando Django...",
      image: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=800",
      duration: "10 semanas",
      students: 632,
      classes: 0,
      link: "/django",
    },
  ];